### ISSUE TITLE
Plastic, Bulbs not craftable in build 1.12.2-1.2.0.

### ISSUE THREAD

**Issue by nicholasBabb** [MoonManModding/EmergingTechnology#12]
In the latest build, bulbs do not seem to be craftable by a standard crafting table (Tested with a Tinkers' Construct Crafting Station in another pack), and their recipes do not appear in a JEI search. Additionally, placing a Shredded Plant or Shredded Plastic item into a processor does not seem to be doing anything. even when supplied with power and water. I tested this in a small test pack containing Agricraft, Mystical Agriculture/Aggraditions, JEI, and EmergingTechnology.

**Comment by DevTimur** [comment]
You need 4 pieces of shredded plants so it produce 1 plastic block.
And yes, bult recipes don't work for me too. JEI tells there is no recipe.

**Comment by MoonManModding** [comment]
Thanks for reporting this 😊 Bit of an oversight on my part with ore dictionary stuff.

Should be fixed in [version 1.2.1](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2843657). 

I will also make it more clear the number of shredded items needed in the Processor for the next release. Let me know if you have any other issues.
