### ISSUE TITLE
Discussion - Lighting and Lamps

### ISSUE THREAD

**Issue by MoonManModding** [MoonManModding/EmergingTechnology#3]
Please post any suggestions and ideas related to [Grow Lights](https://en.wikipedia.org/wiki/Grow_light) here

**Comment by bloodscon** [comment]
Nice looking mod an idea for lights would be to use minecrafts basic progression so at the start basic lights would be crafted using items from overworld like iron, glass, and coal then when you travel to end you use quartz, and glowstone to craft next tier and finally when you get to the end Shulker shells and endstone.  You could also use the same progression for growth media dirt > soul sand > endstone

**Comment by MoonManModding** [comment]
Great idea, that's definitely the plan. I will implement a few basic bulbs and add more progression at a later date once I'm happy it works :)

**Comment by DevTimur** [comment]
How about different lamps and soils effect various platns differently.
For example Sand effect sugarcanes more then dirt or gravel. Green light have more effect on sugarcane aswell.
Carrots and Potatoe grow better in gravel, because root/fruit have more space to grow, and push gravel bits around. Red light got more effect on carrots.
Wheat grow better in dirt or clay, and uv light got more effect.
etc.

Also, how about different liquids got more effect on growth rate, for example Liquid Ender from Thermal Expansion cause Enderlily grow MUCH faster.

If you can't make all combination make an external config file so any modpack developer could make own config with liquids, plants, soils and lamps.

**Comment by MoonManModding** [comment]
Fantastic, I was waiting for someone to bring that up. As you rightly point out making all combinations would be a lot of work, so I'll leave it up to the modpack author to tweak the config files to how they like it. I'll do media and bulbs for the next release, but fluids will probably come a little later as its not as easy.

Thanks for the suggestion! 😎

**Comment by MoonManModding** [comment]
Custom fluids, bulbs and media are available in [version 1.1.8](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2841701) onwards. A guide on adding your own custom features is available [here](https://github.com/MoonManModding/EmergingTechnology/wiki/Custom-Media-Bulbs-Fluids)

Thanks again!
