### ISSUE TITLE
Synthetic Silk

### ISSUE THREAD

**Issue by PlatinumFox** [MoonManModding/EmergingTechnology#65]
Not sure if this is a bug or a feature request.
Synthetic silk does not work as a "fuel" source for the galacticraft grappling hook. 

In case this is a bug i am going to post on GC github as well

**Comment by MoonManModding** [comment]
Hi,

Yes it looks to be Galacticraft unfortunately, they [check for the vanilla String item](https://github.com/micdoodle8/Galacticraft/blob/f85e1dd5ff52ca71e3491c609fb524f270bd77fe/src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/items/ItemGrappleHook.java#L71) rather than using the Ore Dictionary. Hopefully it's an easy fix for them 😎

Thanks for the report!
