### ISSUE TITLE
[BUG] Couple bugs (Light, Harvester, CO2 Diffuser)

### ISSUE THREAD

**Issue by DevTimur** [MoonManModding/EmergingTechnology#66]
1) Hydroponic Lights do not share power anymore.
2) Harvester do not show power level in inventory, even if powered.
2) Harvester break plant before turn to it, wich looks wierd. Maybe add some delay to breaking, untill animation ended. There is no rush, imho.
3) CO2 Diffuser does not shown in Growth Bed statistics.

**Comment by MoonManModding** [comment]
Hi,

Thanks again for your great testing and bug reporting 😁

1. Fixed for next release.
2. Fixed for next release.
3. Fixed for next release. Animations are weird in Minecraft so you may still notice the occasional jerky behaviour however.
4. Currently the CO2 Diffuser shows the boost it provides in its own GUI rather than the grow bed's. I felt it would add uneccessary overhead to have the grow beds 'find' which Diffusers were affecting them, but if you think it's worth it I will try to add it in.

Cheers 😎

**Comment by MoonManModding** [comment]
I think 1-3 should be fixed in [version 1.3.9-beta](https://www.curseforge.com/minecraft/mc-mods/emerging-technology-hydroponics/files/2889339)

Let me know about the Diffuser boost stuff in a new issue if you'd like it as a feature. Thanks again 👍
